version: "3.8"
services:
  app:
    build: ./.docker/php/7.4
    volumes:
      - ./app:/app

  web:
    build: ./.docker/nginx/1.18
    ports:
      - 80:80
    volumes:
      - ./app:/app

  db:
    build: ./.docker/mysql/8
    volumes:
      - db-store:/var/lib/mysql
    tty: true
    ports:
      - 33060:3306

volumes:
  db-store:
